# Generated by Django 4.1.5 on 2023-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgym', '0003_photoalbum_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
