# Generated by Django 4.1.5 on 2023-07-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgym', '0004_photoalbum_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_grad', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tgym.blog')),
            ],
        ),
    ]
